services:
  mosters:
    build:
      context: ./mosters
      dockerfile: Dockerfile
    volumes:
      - ./posters:/app/posters
    ports:
      - 8080:8080
    environment:
      - POSTER_DIR=/posters